### ISSUE TITLE
presence of PromptModel class

### ISSUE THREAD

**Issue by RabirajB** [DhananjayAshok/ConGenBench#1]
Hello there seems to be an issue with the PromptModel in the following line in generate_prompt_data.py
**from prompt_models import PromptModel**
![image](https://github.com/DhananjayAshok/ConGenBench/assets/31617556/0de3493c-0e5d-4aa2-a4a3-b55418d27bff)

**Comment by DhananjayAshok** [comment]
Thanks for catching this. I've uploaded the files, it should be fixed now.

**Comment by RabirajB** [comment]
Hi Dhananjay, thanks for taking care of this, really important finding that can help my research as well
